baseURL = "/"

theme = "biztrox-hugo"
summaryLength = "10"
DefaultContentLanguage = "en"
enableRobotsTXT = true
enableGitInfo = true
disableLanguages = [""] # desable language from here
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
logo = "images/logo.png"
mail = "chetan.prajapati@live.com"
mobile = "+44 7392 339 862"
# Meta data
description = "Experienced and professional statistician offers reliable statistical consulting services online to researchers, businesses and PhD students. Hire RSS(UK) accredited freelance statistician for in-depth data analysis and statistical modelling in R, SPSS, STATA. Ask for statistics help in dissertation, medical statistics"
author = "ISCON Statistical Services"
# google map
#gmapAPI = ""
#mapLatitude = ""
#mapLongitude = ""
#mapMarker = "images/marker.png"
# Google Analitycs
#googleAnalitycsID = "Your ID"

# mailchimp subsciption
mailchimpFormAction = "https://themefisher.us9.list-manage.com/subscribe/post?u=f95ece2732a6e9925f2e70a61&amp;id=b1e227529e" # replace this url with yours
mailchimpFormName = "b_f95ece2732a6e9925f2e70a61_b1e227529e" # replace this code with yours



[Language]

  # English
  [Languages.en]
  languageName = "En"
  languageCode = "en-us"
  weight = 1
  title = "Hire Accredited Statistician Online | Freelance Statistical Consulting"
  home = "Home"

  # navigation
  [Languages.en.menu]

    [[Languages.en.menu.nav]]
    name = "About"
    URL = "/about"
    weight = 2

    [[Languages.en.menu.nav]]
    name = "Service"
    URL = "/service"
    hasChildren = true
    weight = 3


      [[Languages.en.menu.nav]]
      parent = "Service"
      name = "Research Planning & Advice"
      URL = "/service/research-planning-advice/"
      pre = "Get expert statistical advice for your reseach"
      weight = "21"
      [[Languages.en.menu.nav]]
      parent = "Service"
      name = "Data Visualisation"
      URL = "/service/data-visualisation"
      pre = "Your data tells a story, Let's us help you to create it"
      weight = "22"
      [[Languages.en.menu.nav]]
      parent = "Service"
      name = "Statistical Analysis & Modelling"
      URL = "/service/statistical-analysis-modelling"
      pre = "Get in-depth analysis and report from expert statistician"
      weight = "23"
      [[Languages.en.menu.nav]]
      parent = "Service"
      name = "Dissertation statistical consulting"
      URL = "/service/dissertationstatistical-consulting"
      pre = "Let us help you to make your disseration a success with expert statistics help"
      weight = "24"
      [[Languages.en.menu.nav]]
      parent = "Service"
      name = "Survey Design & Analysis"
      URL = "/service/survey-design-analysis"
      pre = "Let us help you design and analyse your survey"
      weight = "25"
      [[Languages.en.menu.nav]]
      parent = "Service"
      name = "Clinical-trials Design & Analysis"
      URL = "/service/clinical-trials-design-analysis"
      pre = "Let us help you to design, conduct and analyse your trial data"
      weight = "27"
      [[Languages.en.menu.nav]]
      parent = "Service"
      name = "Epidemiology & Genetics"
      URL = "/service/epidemiology-genetics"
      pre = "Get help from expert genetic epidemiologist"
      weight = "28"
      [[Languages.en.menu.nav]]
      parent = "Service"
      name = "Statistics Training"
      URL = "/service/statistics-training"
      pre = "Let us help you to empower your collagues with interctive statistics training"
      weight = "29"

    [[Languages.en.menu.nav]]
    name = "Case Studies"
    URL = "/case-studies"
    weight = 4

    [[Languages.en.menu.nav]]
    name = "Learning Centre"
    URL = "/learn-statistics"
    weight = 6


      # Quote Button
      [Languages.en.params.quoteBtn]
      enable = true
      btnText = "Get in touch"
      btnURL = "#"

      # about
      [Languages.en.params.about]
      enable = true
      bgImage = "images/background/about-bg.jpg"
      title = "Who We Are?"
      description = "Excepteur sint occaecat cupidatat non proident sunt culpa qui officia deserunt mollit anim id est laborum."
      [Languages.en.params.about.btn]
      enable = true
      btnText = "Explore More"
      btnURL = "#"

        [[Languages.en.params.about.listLeft]]
        listItem = "Business Services"

        [[Languages.en.params.about.listLeft]]
        listItem = "Audit & Assurance"

        [[Languages.en.params.about.listLeft]]
        listItem = "IT Control Solutions"

        [[Languages.en.params.about.listRight]]
        listItem = "Business Services"

        [[Languages.en.params.about.listRight]]
        listItem = "Audit & Assurance"

        [[Languages.en.params.about.listRight]]
        listItem = "IT Control Solutions"

      # promo video
      [Languages.en.params.promoVideo]
      enable = true
      heading = "Introduction <br> Video"
      bgImage = "images/background/promo-video.jpg"
      videoURL = "https://www.youtube.com/watch?v=6ZfuNTqbHE8"
      title = "Lorem ipsum dolor <br> sit amet con."

      # cta
      [Languages.en.params.cta]
      enable = true
      bgImage = "images/background/cta.jpg"
      title = "Are You Ready to Unlock the Hidden Potential and Value of Your Data?"
      titleSM = "<em>Connect with ISCON and see what we can do for you.</em>"
      btnText = "Let’s get in touch"
      btnURL = "#"

      # clients Logo Slider
      [Languages.en.params.logoSlider]
      enable = true
      title = "Learn how we have helped our clients to drive accurate and meaningful data insights"
      titleSM = "Hear from real ISCON clients"
        [[Languages.en.params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-1.png"
        URL = "#"

        [[Languages.en.params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-2.png"
        URL = "#"

        [[Languages.en.params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-3.png"
        URL = "#"

        [[Languages.en.params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-4.png"
        URL = "#"

        [[Languages.en.params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-5.png"
        URL = "#"

        [[Languages.en.params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-1.png"
        URL = "#"

        [[Languages.en.params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-2.png"
        URL = "#"

        [[Languages.en.params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-3.png"
        URL = "#"

        [[Languages.en.params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-4.png"
        URL = "#"

        [[Languages.en.params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-5.png"
        URL = "#"

      # footer
      [Languages.en.params.footer]
      logo = "/images/logo-footer.png"
      content = "62 Maple close, Bristol, BS34 6HH"
      email = "help@isocon-statistics.com"

      # service links
      services = "Services"

      # quickLinks
      quickLink = "Quick Link"

      # subscribe
      subscribe = "Subscribe Us"
      subscribeContent = "Lorem ipsum dolor sit amet, consect etur adipisicing. elit sed do eiusmod."

      # copyright
      copyright = "ISCON Statistical Services ©2020 All Right Reserved"

        # social icon
        [[Languages.en.params.footer.socialIcon]]
        icon = "ti-facebook"
        URL = "#"

        [[Languages.en.params.footer.socialIcon]]
        icon = "ti-twitter-alt"
        URL = "#"

        [[Languages.en.params.footer.socialIcon]]
        icon = "ti-vimeo-alt"
        URL = "#"

        [[Languages.en.params.footer.socialIcon]]
        icon = "ti-linkedin"
        URL = "#"

        # service links
        [[Languages.en.params.footer.service]]
        serviceItem = "Company History"
        URL = "#"

        [[Languages.en.params.footer.service]]
        serviceItem = "About Us"
        URL = "#"

        [[Languages.en.params.footer.service]]
        serviceItem = "Contact Us"
        URL = "#"

        [[Languages.en.params.footer.service]]
        serviceItem = "Service"
        URL = "#"

        [[Languages.en.params.footer.service]]
        serviceItem = "Privacy Policy"
        URL = "#"

        # quick links
        [[Languages.en.params.footer.quickLinks]]
        quickLinkItem = "Pricing"
        URL = "#"

        [[Languages.en.params.footer.quickLinks]]
        quickLinkItem = "FAQs"
        URL = "#"

        [[Languages.en.params.footer.quickLinks]]
        quickLinkItem = "Contact Us"
        URL = "#"

        [[Languages.en.params.footer.quickLinks]]
        quickLinkItem = "Service"
        URL = "#"

        [[Languages.en.params.footer.quickLinks]]
        quickLinkItem = "Privacy Policy"
        URL = "#"

        # bottom links
        [[Languages.en.params.footer.links]]
          name = "Sitemap"
          URL = "#"

        [[Languages.en.params.footer.links]]
          name = "Terms of Use"
          URL = "#"

        [[Languages.en.params.footer.links]]
          name = "Privacy & Cookies Policy"
          URL = "#"


      # share blog post
      [[Languages.en.params.sharePost]]
      icon = "ti-facebook"
      URL = "#"

      [[Languages.en.params.sharePost]]
      icon = "ti-twitter-alt"
      URL = "#"

      [[Languages.en.params.sharePost]]
      icon = "ti-linkedin"
      URL = "#"

      [[Languages.en.params.sharePost]]
      icon = "ti-google"
      URL = "#"

