baseURL = ""
theme = "biztrox-hugo"
summaryLength = "10"
DefaultContentLanguage = "en"
disableLanguages = [""] # desable language from here

[params]
logo = "images/logo=n.png"
mail = "chetan@statistican-online.com"
mobile = "+44 7392 339 862"
# Meta data
description = "Statistical Consulting"
author = "themefisher"
# google map
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
mapLatitude = "51.5223477"
mapLongitude = "-0.1622023"
mapMarker = "images/marker.png"
# Google Analitycs
googleAnalitycsID = "Your ID"

# mailchimp subsciption
mailchimpFormAction = "https://themefisher.us9.list-manage.com/subscribe/post?u=f95ece2732a6e9925f2e70a61&amp;id=b1e227529e" # replace this url with yours
mailchimpFormName = "b_f95ece2732a6e9925f2e70a61_b1e227529e" # replace this code with yours



[Language]
  
  # English
  [Languages.en]
  languageName = "En"
  languageCode = "en-us"
  weight = 1
  title = "Statistical Consulting"
  home = "Home"

  # navigation
  [Languages.en.menu]
      
    [[Languages.en.menu.nav]]
    name = "About"
    URL = "/about"
    weight = 2
    
    [[Languages.en.menu.nav]]
    name = "Service"
    URL = "/service"
    hasChildren = true
    weight = 3

    
      [[Languages.en.menu.nav]]
      parent = "Service"
      name = "Research Planning & Advice"
      URL = "/service/research-planning-advice"
      pre = "Menu Sub Text Here"
      [[Languages.en.menu.nav]]
      parent = "Service"
      name = "Data collection & Management"
      URL = "/service/data-collection-management"
      pre = "Menu Sub Text Here"
      [[Languages.en.menu.nav]]
      parent = "Service"
      name = "Data Visualisation"
      URL = "/service/data-visualisation"
      pre = "Menu Sub Text Here"
      [[Languages.en.menu.nav]]
      parent = "Service"
      name = "Statistical Analysis & Modelling"
      URL = "/service/statistical-analysis-modelling"
      pre = "Menu Sub Text Here"
      [[Languages.en.menu.nav]]
      parent = "Service"
      name = "Predictive Analytics"
      URL = "/service/predictive-analytics"
      pre = "Menu Sub Text Here"
      [[Languages.en.menu.nav]]
      parent = "Service"
      name = "Survey Design & Analysis"
      URL = "/service/survey-design-analysis"
      pre = "Menu Sub Text Here"
      [[Languages.en.menu.nav]]
      parent = "Service"
      name = "Clinical-trials Design & Analysis"
      URL = "/service/clinical-trials-design-analysis"
      pre = "Menu Sub Text Here"
      [[Languages.en.menu.nav]]
      parent = "Service"
      name = "Statistical review of proposal"
      URL = "/service/statistical-review-proposal"
      pre = "Menu Sub Text Here"
      [[Languages.en.menu.nav]]
      parent = "Service"
      name = "Statistics training"
      URL = "/service/statistics-training"
      pre = "Menu Sub Text Here"
    
    [[Languages.en.menu.nav]]
    name = "Case Studies"
    URL = "/case-studies"
    weight = 4
    
    [[Languages.en.menu.nav]]
    name = "Learn Statistics"
    URL = "/learn-statistics"
    weight = 6


      # Quote Button
      [Languages.en.params.quoteBtn]
      enable = true
      btnText = "Send us message"
      btnURL = "#"

      # about
      [Languages.en.params.about]
      enable = true
      bgImage = "images/background/about-bg.jpg"
      title = "Who We Are?"
      description = "Excepteur sint occaecat cupidatat non proident sunt culpa qui officia deserunt mollit anim id est laborum."
      [Languages.en.params.about.btn]
      enable = true
      btnText = "Explore More"
      btnURL = "#"

        [[Languages.en.params.about.listLeft]]
        listItem = "Business Services"

        [[Languages.en.params.about.listLeft]]
        listItem = "Audit & Assurance"
        
        [[Languages.en.params.about.listLeft]]
        listItem = "IT Control Solutions"

        [[Languages.en.params.about.listRight]]
        listItem = "Business Services"

        [[Languages.en.params.about.listRight]]
        listItem = "Audit & Assurance"
        
        [[Languages.en.params.about.listRight]]
        listItem = "IT Control Solutions"

      # promo video
      [Languages.en.params.promoVideo]
      enable = true
      heading = "Introduction <br> Video"
      bgImage = "images/background/promo-video.jpg"
      videoURL = "https://www.youtube.com/watch?v=6ZfuNTqbHE8"
      title = "Lorem ipsum dolor <br> sit amet con."

      # cta
      [Languages.en.params.cta]
      enable = true
      bgImage = "images/background/cta.jpg"
      title = "Are You Ready to Unlock the Hidden Potential and Value of Your Data?"
      titleSM = "<em>Connect with ISCON and see what we can do for you.</em>"
      btnText = "Let’s get in touch"
      btnURL = "#"

      # clients Logo Slider
      [Languages.en.params.logoSlider]
      enable = true
      title = "Learn how we have helped our clients to drive accurate and meaningful data insights"
      titleSM = "Hear from real ISCON clients"
        [[Languages.en.params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-1.png"
        URL = "#"
        
        [[Languages.en.params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-2.png"
        URL = "#"
        
        [[Languages.en.params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-3.png"
        URL = "#"
        
        [[Languages.en.params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-4.png"
        URL = "#"
        
        [[Languages.en.params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-5.png"
        URL = "#"
        
        [[Languages.en.params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-1.png"
        URL = "#"
        
        [[Languages.en.params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-2.png"
        URL = "#"
        
        [[Languages.en.params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-3.png"
        URL = "#"
        
        [[Languages.en.params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-4.png"
        URL = "#"
        
        [[Languages.en.params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-5.png"
        URL = "#"

      # footer
      [Languages.en.params.footer]
      logo = "images/logo-white.png"
      content = "Lorem ipsum dolor amet consectetur adipisicing elit sed eiusm tempor incididunt labore dolore magna aliqua enim."

      # service links
      services = "Services"
      
      # quickLinks
      quickLink = "Quick Link"

      # subscribe
      subscribe = "Subscribe Us"
      subscribeContent = "Lorem ipsum dolor sit amet, consect etur adipisicing. elit sed do eiusmod."

      # copyright
      copyright = "Bizpro</span> &copy; 2017 All Right Reserved"

        # social icon
        [[Languages.en.params.footer.socialIcon]]
        icon = "ti-facebook"
        URL = "#"

        [[Languages.en.params.footer.socialIcon]]
        icon = "ti-twitter-alt"
        URL = "#"
        
        [[Languages.en.params.footer.socialIcon]]
        icon = "ti-vimeo-alt"
        URL = "#"
        
        [[Languages.en.params.footer.socialIcon]]
        icon = "ti-linkedin"
        URL = "#"

        # service links
        [[Languages.en.params.footer.service]]
        serviceItem = "Company History"
        URL = "#"
        
        [[Languages.en.params.footer.service]]
        serviceItem = "About Us"
        URL = "#"
        
        [[Languages.en.params.footer.service]]
        serviceItem = "Contact Us"
        URL = "#"
        
        [[Languages.en.params.footer.service]]
        serviceItem = "Service"
        URL = "#"
        
        [[Languages.en.params.footer.service]]
        serviceItem = "Privacy Policy"
        URL = "#"

        # quick links
        [[Languages.en.params.footer.quickLinks]]
        quickLinkItem = "Pricing"
        URL = "#"
        
        [[Languages.en.params.footer.quickLinks]]
        quickLinkItem = "FAQs"
        URL = "#"
        
        [[Languages.en.params.footer.quickLinks]]
        quickLinkItem = "Contact Us"
        URL = "#"
        
        [[Languages.en.params.footer.quickLinks]]
        quickLinkItem = "Service"
        URL = "#"
        
        [[Languages.en.params.footer.quickLinks]]
        quickLinkItem = "Privacy Policy"
        URL = "#"

        # bottom links
        [[Languages.en.params.footer.links]]
          name = "Legal"
          URL = "#"
            
        [[Languages.en.params.footer.links]]
          name = "Sitemap"
          URL = "#"
            
        [[Languages.en.params.footer.links]]
          name = "Privacy Policy"
          URL = "#"
            
        [[Languages.en.params.footer.links]]
          name = "Terms & Conditions"
          URL = "#"

      # share blog post
      [[Languages.en.params.sharePost]]
      icon = "ti-facebook"
      URL = "#"
      
      [[Languages.en.params.sharePost]]
      icon = "ti-twitter-alt"
      URL = "#"
      
      [[Languages.en.params.sharePost]]
      icon = "ti-linkedin"
      URL = "#"
      
      [[Languages.en.params.sharePost]]
      icon = "ti-google"
      URL = "#"
          
